-- StudentProjectHub — full schema (PostgreSQL / Supabase)
--
-- Run once: Supabase dashboard -> SQL Editor -> New query -> paste -> Run.
--
-- Phase 1 only writes to users / student_profiles / client_profiles, but every
-- table is created now so later phases need no migration.
--
-- Note: this app connects to Postgres directly as the postgres role, which
-- bypasses Row Level Security. Do not expose these tables through the Supabase
-- anon key without writing RLS policies first.

CREATE TABLE IF NOT EXISTS users (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname   VARCHAR(150) NOT NULL,
    email      VARCHAR(150) UNIQUE NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(20) NOT NULL CHECK (role IN ('student','client','admin')),
    status     VARCHAR(20) NOT NULL DEFAULT 'active'
               CHECK (status IN ('active','suspended','pending')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

CREATE TABLE IF NOT EXISTS student_profiles (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    university    VARCHAR(200),
    department    VARCHAR(200),
    level         VARCHAR(50),
    bio           TEXT,
    phone         VARCHAR(50),
    profile_image VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS client_profiles (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             INT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    company_name        VARCHAR(200),
    company_description TEXT,
    website             VARCHAR(255),
    phone               VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS skills (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS student_skills (
    student_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    skill_id   INT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (student_id, skill_id)
);

CREATE TABLE IF NOT EXISTS projects (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id         INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title             VARCHAR(255) NOT NULL,
    description       TEXT NOT NULL,
    category          VARCHAR(100),
    difficulty        VARCHAR(20) DEFAULT 'beginner'
                      CHECK (difficulty IN ('beginner','intermediate','advanced')),
    project_type      VARCHAR(20) DEFAULT 'experience'
                      CHECK (project_type IN ('experience','reward','client')),
    budget            NUMERIC(10,2) DEFAULT 0,
    deadline          DATE,
    max_students      INT DEFAULT 1,
    status            VARCHAR(20) NOT NULL DEFAULT 'draft'
                      CHECK (status IN ('draft','open','assigned','submitted','completed','cancelled')),
    requirements_file VARCHAR(255),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_projects_status ON projects (status);
CREATE INDEX IF NOT EXISTS idx_projects_client ON projects (client_id);

CREATE TABLE IF NOT EXISTS project_skills (
    project_id INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    skill_id   INT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, skill_id)
);

CREATE TABLE IF NOT EXISTS applications (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    student_id   INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    cover_letter TEXT,
    status       VARCHAR(20) NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','accepted','rejected','withdrawn')),
    applied_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (project_id, student_id)
);

CREATE TABLE IF NOT EXISTS assignments (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    student_id   INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    assigned_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at   TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    status       VARCHAR(20) NOT NULL DEFAULT 'assigned'
                 CHECK (status IN ('assigned','in_progress','submitted','revision','approved','completed')),
    UNIQUE (project_id, student_id)
);

CREATE TABLE IF NOT EXISTS submissions (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id INT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    version       INT NOT NULL DEFAULT 1,
    file_path     VARCHAR(255),
    comment       TEXT,
    submitted_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS assessments (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id INT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    score         NUMERIC(5,2),
    feedback      TEXT,
    decision      VARCHAR(20) CHECK (decision IN ('approved','revision')),
    assessed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS messages (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id   INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    receiver_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id  INT REFERENCES projects(id) ON DELETE SET NULL,
    message     TEXT NOT NULL,
    read_at     TIMESTAMPTZ,
    sent_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ratings (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    reviewer_id      INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reviewed_user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating           INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment          TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS certificates (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id         INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id         INT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    certificate_number VARCHAR(100) UNIQUE NOT NULL,
    certificate_file   VARCHAR(255),
    issued_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO skills (name) VALUES
('Python'),('Flask'),('Django'),('JavaScript'),('React'),('Node.js'),
('MySQL'),('PostgreSQL'),('MongoDB'),('HTML'),('CSS'),('PHP'),('Java'),
('C++'),('Machine Learning'),('Data Analysis'),('UI/UX Design'),
('Figma'),('Cybersecurity'),('Networking'),('Technical Writing'),
('Digital Marketing'),('Android'),('Flutter'),('Git')
ON CONFLICT (name) DO NOTHING;
